/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_dancingdemon_pcsx_PCSX_ReARMed */

#ifndef _Included_net_dancingdemon_pcsx_PCSX_ReARMed
#define _Included_net_dancingdemon_pcsx_PCSX_ReARMed
#ifdef __cplusplus
extern "C" {
#endif
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_NONE
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_NONE 0L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_MAIN
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_MAIN 1L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS 2L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_EMU
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_EMU 3L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_VID
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_VID 4L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_AUD
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_AUD 5L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_INP
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_INP 6L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_BIOS
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_BIOS 7L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_SAVE
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_SETTINGS_SAVE 8L
#undef net_dancingdemon_pcsx_PCSX_ReARMed_MENU_LOAD_GAME
#define net_dancingdemon_pcsx_PCSX_ReARMed_MENU_LOAD_GAME 9L
/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeOnStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeOnStart
  (JNIEnv *, jclass);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeOnResume
  (JNIEnv *, jclass);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeOnStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeOnStop
  (JNIEnv *, jclass);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeSetSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeSetSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativePrefsChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativePrefsChanged
  (JNIEnv *, jclass);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeEmuPauseUnpause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeEmuPauseUnpause
  (JNIEnv *, jclass);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeEmuLoadGame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeEmuLoadGame
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_dancingdemon_pcsx_PCSX_ReARMed
 * Method:    nativeEmuUnloadGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dancingdemon_pcsx_PCSX_1ReARMed_nativeEmuUnloadGame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
